config/routes.rb
Rails.application.routes.draw do
  resources :contracts
  resources :people
  resources :machines
  resources :organizations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contract.rb
class Contract < ApplicationRecord
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_params
      params.require(:contract).permit(:dated, :people, :service_from, :service_to, :preferred_date, :time)
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= form_with(model: contract, local: true) do |form| %>
  <% if contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dated %>
    <%= form.date_select :dated %>
  </div>

  <div class="field">
    <%= form.label :people %>
    <%= form.text_field :people %>
  </div>

  <div class="field">
    <%= form.label :service_from %>
    <%= form.date_select :service_from %>
  </div>

  <div class="field">
    <%= form.label :service_to %>
    <%= form.date_select :service_to %>
  </div>

  <div class="field">
    <%= form.label :preferred_date %>
    <%= form.text_field :preferred_date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Dated</th>
      <th>People</th>
      <th>Service from</th>
      <th>Service to</th>
      <th>Preferred date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.dated %></td>
        <td><%= contract.people %></td>
        <td><%= contract.service_from %></td>
        <td><%= contract.service_to %></td>
        <td><%= contract.preferred_date %></td>
        <td><%= contract.time %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<h1>New Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dated:</strong>
  <%= @contract.dated %>
</p>

<p>
  <strong>People:</strong>
  <%= @contract.people %>
</p>

<p>
  <strong>Service from:</strong>
  <%= @contract.service_from %>
</p>

<p>
  <strong>Service to:</strong>
  <%= @contract.service_to %>
</p>

<p>
  <strong>Preferred date:</strong>
  <%= @contract.preferred_date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @contract.time %>
</p>

<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>