config/routes.rb
Rails.application.routes.draw do
  resources :contracts
  resources :people
  resources :machines
  resources :organizations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/machine.rb
class Machine < ApplicationRecord
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:name, :mac, :cpu, :ram, :hdd, :optical_drive, :os, :purchase_date)
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_with(model: machine, local: true) do |form| %>
  <% if machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mac %>
    <%= form.text_field :mac %>
  </div>

  <div class="field">
    <%= form.label :cpu %>
    <%= form.text_field :cpu %>
  </div>

  <div class="field">
    <%= form.label :ram %>
    <%= form.text_field :ram %>
  </div>

  <div class="field">
    <%= form.label :hdd %>
    <%= form.text_field :hdd %>
  </div>

  <div class="field">
    <%= form.label :optical_drive %>
    <%= form.text_field :optical_drive %>
  </div>

  <div class="field">
    <%= form.label :os %>
    <%= form.text_field :os %>
  </div>

  <div class="field">
    <%= form.label :purchase_date %>
    <%= form.date_select :purchase_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/machines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Machines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mac</th>
      <th>Cpu</th>
      <th>Ram</th>
      <th>Hdd</th>
      <th>Optical drive</th>
      <th>Os</th>
      <th>Purchase date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.name %></td>
        <td><%= machine.mac %></td>
        <td><%= machine.cpu %></td>
        <td><%= machine.ram %></td>
        <td><%= machine.hdd %></td>
        <td><%= machine.optical_drive %></td>
        <td><%= machine.os %></td>
        <td><%= machine.purchase_date %></td>
        <td><%= link_to 'Show', machine %></td>
        <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
        <td><%= link_to 'Destroy', machine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Machine', new_machine_path %>

app/views/machines/new.html.erb
<h1>New Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Back', machines_path %>

app/views/machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @machine.name %>
</p>

<p>
  <strong>Mac:</strong>
  <%= @machine.mac %>
</p>

<p>
  <strong>Cpu:</strong>
  <%= @machine.cpu %>
</p>

<p>
  <strong>Ram:</strong>
  <%= @machine.ram %>
</p>

<p>
  <strong>Hdd:</strong>
  <%= @machine.hdd %>
</p>

<p>
  <strong>Optical drive:</strong>
  <%= @machine.optical_drive %>
</p>

<p>
  <strong>Os:</strong>
  <%= @machine.os %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @machine.purchase_date %>
</p>

<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>